name: api_CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/api_CD.yml'

env:
  PNPM_VERSION: '10.13.1'
  NODE_VERSION: '22'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'apps/api'
